use_frameworks!

target 'SwiftEssentialsKit_Example' do
  pod 'SwiftEssentialsKit', :path => '../'

  target 'SwiftEssentialsKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
